#ifndef EMU_EXECUTE_H_
#define EMU_EXECUTE_H_

typedef enum{

    ADDR_REG,
    ADDR_REG_INDIRECT,
    ADDR_REG_EIGHT_IMED,
    ADDR_REG_SIXTEEN_IMED,
    ADDR_PC_COND_RELATIVE_SIXTEEN,
    ADDR_PC_RELATIVE_SIXTEEN,
    ADDR_IMMEDIATE_EIGHT,
    ADDR_IMMEDIATE_SIXTEEN

} EMU_Addressing_Modes;

#endif